export enum RouteNames {
  MAIN = '/',
  ORDER = '/order',
  ORDER_ID = '/order/:id',
  PARKING = '/parking',
  INSURANCE = '/insurance',
  PETROL = '/petrol',
  SERVICE = '/service',
  LOGIN = '/login',
  ADMIN = 'admin',
  ADMIN_CARS_LIST = 'cars-list',
  ADMIN_ORDER_LIST = 'order-list',
  ADMIN_CITY_LIST = 'city-list',
  ADMIN_POINT_LIST = 'point-list',
}
