export enum RouteNames {
  MAIN = '/',
  ORDER = '/order',
  ORDER_ID = '/order/:id',
  PARKING = '/parking',
  INSURANCE = '/insurance',
  PETROL = '/petrol',
  SERVICE = '/service',
  LOGIN = '/login',
  ADMIN = 'admin',
  ADMIN_CARS_LIST = 'cars-list',
  ADMIN_ORDER_LIST = 'order-list',
  ADMIN_CITY_LIST = 'city-list',
  ADMIN_POINT_LIST = 'point-list',
  ADMIN_CATEGORY_LIST = 'category-list',
  ADMIN_RATE_LIST = 'rate-list',
  ADMIN_RATE_TYPE_LIST = 'rate-type-list',
  ADMIN_ORDER_STATUS_LIST = 'order-status-list',
  ADMIN_CAR_CREATE = 'car-create',
}
